import numpy as np
import pandas as pd
from typing import Union, List, Dict
import time

from .core import (
    rdacca_hp,
    _rdacca_hp_multi,
    _rdacca_hp_single,
    _rda_hp_individual_fast,
    _get_hp_cached_structures,
    _get_hp_individual_r2_weights,
    _prepare_dbrda_vegan_response,
    _dbrda_subset_r2_values_fast,
)
from .utils import (
    sanitize_tabular_input,
    preprocess_predictor_dataframe,
    preprocess_grouped_predictors,
    prepare_dbrda_response,
)


def _build_permutation_engine(iv, method, type, scale, n_perm, add, sqrt_dist, n_axes, dbrdatype,
                              ordered_factors, categorical_factors, kwargs,
                              cca_rng=None):
    """
    Build a lightweight evaluator for permutation runs without changing the public API
    or output structure.
    """
    core_kwargs = dict(kwargs)
    core_kwargs["n_perm"] = n_perm
    core_kwargs["add"] = add
    core_kwargs["sqrt_dist"] = sqrt_dist
    core_kwargs["n_axes"] = n_axes
    core_kwargs["dbrdatype"] = dbrdatype
    core_kwargs["ordered_factors"] = ordered_factors
    core_kwargs["categorical_factors"] = categorical_factors
    if method == "CCA" and type == "adjR2":
        core_kwargs["_cca_rng"] = (
            cca_rng if cca_rng is not None else np.random.default_rng()
        )

    # Single DataFrame input in rdacca_hp() is internally converted into logical
    # predictor groups (including categorical / ordered factor expansions).
    # Do that once here, then only permute the already-prepared groups.
    if isinstance(iv, pd.DataFrame):
        _, encoded_groups, _ = preprocess_predictor_dataframe(
            iv,
            ordered_factors=ordered_factors,
            categorical_factors=categorical_factors,
            warn=False,
        )

        def evaluate(dv_current, iv_current):
            return _rdacca_hp_multi(
                dv=dv_current,
                iv=iv_current,
                method=method,
                type=type,
                scale=scale,
                var_part=False,
                **core_kwargs,
            )

        return encoded_groups, evaluate

    if isinstance(iv, (dict, list)):
        grouped_iv = preprocess_grouped_predictors(
            iv,
            ordered_factors=ordered_factors,
            categorical_factors=categorical_factors,
            warn=False,
        )

        def evaluate(dv_current, iv_current):
            return _rdacca_hp_multi(
                dv=dv_current,
                iv=iv_current,
                method=method,
                type=type,
                scale=scale,
                var_part=False,
                **core_kwargs,
            )

        return grouped_iv, evaluate

    def evaluate(dv_current, iv_current):
        return _rdacca_hp_single(
            dv=dv_current,
            iv=iv_current,
            method=method,
            type=type,
            scale=scale,
            var_part=False,
            **core_kwargs,
        )

    return iv, evaluate


def _recommended_rda_batch_size(n_samples: int, n_columns: int, n_responses: int) -> int:
    """Choose a conservative batch size for vectorized RDA permutations.

    The fast path stores a small stack of permuted X matrices plus their Gram and
    X'Y cross-products.  Keeping the working set modest is important for the web
    application and for larger ecological data sets, so the target is roughly
    64 MiB and the hard cap is 256 permutations per batch.
    """
    bytes_per_perm = 8 * (
        n_samples * max(n_columns, 1)
        + max(n_columns, 1) ** 2
        + max(n_columns, 1) * max(n_responses, 1)
    )
    if bytes_per_perm <= 0:
        return 1
    target_bytes = 64 * 1024 * 1024
    return max(1, min(256, target_bytes // bytes_per_perm))


def _rda_permutation_individuals_batched(
    dv,
    base_groups,
    n_random: int,
    n_samples: int,
    rng,
    mode: str,
    type: str,
    scale: bool,
    verbose: bool,
    skip_failed: bool,
):
    """Evaluate RDA permutation HP values in vectorized batches.

    This keeps exactly the same permutation scheme as the existing implementation:
    original DataFrame variables are permuted independently, while explicit
    dict/list groups share one row permutation.  The random permutations are still
    generated by the same ``numpy.random.Generator`` in the same order.

    The numerical speedup comes from evaluating one subset across many permutations
    at once with NumPy's stacked linear algebra instead of dispatching roughly one
    million tiny ``np.linalg.solve`` calls through the Python loop for the Doubs
    benchmark.
    """
    groups = []
    for group in base_groups:
        arr = np.asarray(group, dtype=float)
        if arr.ndim == 1:
            arr = arr.reshape(-1, 1)
        if arr.shape[0] != n_samples:
            raise ValueError("Dependent and independent variables must have the same number of rows.")
        groups.append(arr)

    if not groups:
        return np.empty((n_random, 0), dtype=float), 0

    Y_original = np.asarray(dv, dtype=float)
    if Y_original.ndim == 1:
        Y_original = Y_original.reshape(-1, 1)
    if Y_original.shape[0] != n_samples:
        raise ValueError("Dependent and independent variables must have the same number of rows.")

    Y = Y_original
    if scale:
        Y = (Y - np.mean(Y, axis=0)) / np.std(Y, axis=0)
    Yc = Y - np.mean(Y, axis=0, keepdims=True)
    total_ss = float(np.sum(Yc * Yc))

    n_items = len(groups)
    widths = [g.shape[1] for g in groups]
    starts = np.cumsum([0] + widths).astype(np.intp)
    n_columns = int(starts[-1])
    n_responses = Yc.shape[1]

    _, _, _, _, combo_indices, _ = _get_hp_cached_structures(n_items)
    combo_columns = []
    combo_widths = []
    for selected_groups in combo_indices:
        cols = []
        for g in selected_groups:
            cols.extend(range(int(starts[g]), int(starts[g + 1])))
        cols = np.asarray(cols, dtype=np.intp)
        combo_columns.append(cols)
        combo_widths.append(int(cols.size))

    weights = _get_hp_individual_r2_weights(n_items)
    out = np.full((n_random, n_items), np.nan, dtype=float)
    failed_perms = 0

    batch_size = _recommended_rda_batch_size(n_samples, n_columns, n_responses)
    next_progress = 100

    for batch_start in range(0, n_random, batch_size):
        batch_end = min(n_random, batch_start + batch_size)
        b = batch_end - batch_start
        X_batch = np.empty((b, n_samples, n_columns), dtype=float)

        # Generate permutations in exactly the same order as the previous fast loop.
        for local_i in range(b):
            if mode == "independent_groups":
                for g, group in enumerate(groups):
                    perm = rng.permutation(n_samples)
                    X_batch[local_i, :, starts[g]:starts[g + 1]] = group[perm, :]
            else:
                perm = rng.permutation(n_samples)
                for g, group in enumerate(groups):
                    X_batch[local_i, :, starts[g]:starts[g + 1]] = group[perm, :]

        # Match the first-round Gram implementation: center each permuted design
        # before checking rank/conditioning and forming cross-products.
        Xc_batch = X_batch - np.mean(X_batch, axis=1, keepdims=True)

        if n_columns == 0:
            safe_mask = np.zeros(b, dtype=bool)
        else:
            try:
                ranks = np.linalg.matrix_rank(Xc_batch)
                if n_columns > 1:
                    conds = np.linalg.cond(Xc_batch)
                    safe_mask = (ranks == n_columns) & np.isfinite(conds) & (conds < 1e8)
                else:
                    safe_mask = ranks == 1
            except np.linalg.LinAlgError:
                safe_mask = np.zeros(b, dtype=bool)

        safe_local = np.flatnonzero(safe_mask)
        batch_fast_failed = False

        if safe_local.size:
            Xsafe = Xc_batch[safe_local]
            gram = np.matmul(Xsafe.transpose(0, 2, 1), Xsafe)
            cross = np.matmul(
                Xsafe.transpose(0, 2, 1),
                np.broadcast_to(Yc, (safe_local.size, n_samples, n_responses)),
            )
            r2_values = np.empty((safe_local.size, len(combo_columns)), dtype=float)

            try:
                for combo_i, (cols, k) in enumerate(zip(combo_columns, combo_widths)):
                    if total_ss <= 0.0:
                        r = np.ones(safe_local.size, dtype=float)
                    else:
                        Gs = gram[:, cols][:, :, cols]
                        Cs = cross[:, cols, :]
                        beta = np.linalg.solve(Gs, Cs)
                        explained_ss = np.sum(Cs * beta, axis=(1, 2))
                        r = explained_ss / total_ss

                        # Same tiny numerical guards as the single-permutation kernel.
                        r = np.where(
                            (r > 1.0) & (r < 1.0 + 1e-12),
                            1.0,
                            r,
                        )
                        r = np.where(
                            (r < 0.0) & (r > -1e-12),
                            0.0,
                            r,
                        )

                    if type == "adjR2":
                        if n_samples <= k + 1:
                            r = np.zeros_like(r)
                        else:
                            r = 1.0 - (1.0 - r) * (n_samples - 1) / (n_samples - k - 1)
                    r2_values[:, combo_i] = r

                raw_individual = r2_values @ weights.T
                # Use Python's round scalar-by-scalar to preserve the package's
                # historical four-decimal permutation values exactly.
                for pos, local_i in enumerate(safe_local):
                    for j in range(n_items):
                        out[batch_start + local_i, j] = round(float(raw_individual[pos, j]), 4)
            except np.linalg.LinAlgError:
                # Extremely rare for a design that passed the rank/condition gate.
                # Fall back to the first-round implementation for this whole batch.
                batch_fast_failed = True
                out[batch_start:batch_end, :] = np.nan

        fallback_local = np.arange(b, dtype=np.intp) if batch_fast_failed else np.flatnonzero(~safe_mask)
        for local_i in fallback_local:
            try:
                permuted_groups = [
                    X_batch[local_i, :, starts[g]:starts[g + 1]]
                    for g in range(n_items)
                ]
                out[batch_start + local_i, :] = _rda_hp_individual_fast(
                    Y_original,
                    permuted_groups,
                    type=type,
                    scale=scale,
                )
            except Exception:
                if not skip_failed:
                    raise
                failed_perms += 1
                out[batch_start + local_i, :] = np.nan

        if verbose:
            while next_progress <= batch_end:
                print(f"  Completed {next_progress}/{n_random} permutations")
                next_progress += 100

    return out, failed_perms



def _dbrda_permutation_individuals_batched(
    dv_dist,
    base_groups,
    n_random: int,
    n_samples: int,
    rng,
    mode: str,
    type: str,
    add,
    sqrt_dist: bool,
    verbose: bool,
    skip_failed: bool,
):
    """Evaluate default vegan-style db-RDA permutation HP values in batches.

    The response dissimilarity matrix is fixed while explanatory variables are
    permuted, so the Gower-centred response matrix B and trace(B) are prepared
    once for the entire permutation test.  Within each batch, the full design
    cross-products

        G = X'X
        Q = X' B X

    are computed once per permutation and then sliced for every logical subset.
    HP Individual values are obtained directly from the cached subset-R2 ->
    Individual linear map, avoiding full commonality/result construction for
    each randomized run.

    This fast path is used only for dbrdatype="dbrda".  Rank-deficient or very
    ill-conditioned permuted designs fall back to the numerically safer Round-1
    subset evaluator.
    """
    groups = []
    for group in base_groups:
        arr = np.asarray(group, dtype=float)
        if arr.ndim == 1:
            arr = arr.reshape(-1, 1)
        if arr.shape[0] != n_samples:
            raise ValueError(
                "Dependent and independent variables must have the same number of rows."
            )
        groups.append(arr)

    if not groups:
        return np.empty((n_random, 0), dtype=float), 0

    B, total_inertia = _prepare_dbrda_vegan_response(
        dv_dist, add=add, sqrt_dist=sqrt_dist
    )
    if B.shape[0] != n_samples:
        raise ValueError(
            "Dependent and independent variables must have the same number of rows."
        )

    n_items = len(groups)
    widths = [g.shape[1] for g in groups]
    starts = np.cumsum([0] + widths).astype(np.intp)
    n_columns = int(starts[-1])

    _, _, _, _, combo_indices, _ = _get_hp_cached_structures(n_items)
    combo_columns = []
    combo_widths = []
    for selected_groups in combo_indices:
        cols = []
        for g in selected_groups:
            cols.extend(range(int(starts[g]), int(starts[g + 1])))
        cols = np.asarray(cols, dtype=np.intp)
        combo_columns.append(cols)
        combo_widths.append(int(cols.size))

    weights = _get_hp_individual_r2_weights(n_items)
    out = np.full((n_random, n_items), np.nan, dtype=float)
    failed_perms = 0

    # Reuse the same conservative memory policy as the RDA Round-2 path.  The
    # Q=X'BX workspace is p x p, so n_responses=p gives an appropriate estimate.
    batch_size = _recommended_rda_batch_size(n_samples, n_columns, n_columns)
    next_progress = 100

    for batch_start in range(0, n_random, batch_size):
        batch_end = min(n_random, batch_start + batch_size)
        b = batch_end - batch_start
        X_batch = np.empty((b, n_samples, n_columns), dtype=float)

        # Preserve the exact RNG call order used by the existing permutation path.
        for local_i in range(b):
            if mode == "independent_groups":
                for g, group in enumerate(groups):
                    perm = rng.permutation(n_samples)
                    X_batch[local_i, :, starts[g]:starts[g + 1]] = group[perm, :]
            else:
                perm = rng.permutation(n_samples)
                for g, group in enumerate(groups):
                    X_batch[local_i, :, starts[g]:starts[g + 1]] = group[perm, :]

        Xc_batch = X_batch - np.mean(X_batch, axis=1, keepdims=True)

        if n_columns == 0:
            safe_mask = np.zeros(b, dtype=bool)
        else:
            try:
                ranks = np.linalg.matrix_rank(Xc_batch)
                if n_columns > 1:
                    conds = np.linalg.cond(Xc_batch)
                    safe_mask = (
                        (ranks == n_columns)
                        & np.isfinite(conds)
                        & (conds < 1e8)
                    )
                else:
                    safe_mask = ranks == 1
            except np.linalg.LinAlgError:
                safe_mask = np.zeros(b, dtype=bool)

        safe_local = np.flatnonzero(safe_mask)
        batch_fast_failed = False

        if safe_local.size:
            Xsafe = Xc_batch[safe_local]
            Xt = Xsafe.transpose(0, 2, 1)
            gram = np.matmul(Xt, Xsafe)

            # B is fixed across all permutations. np.matmul broadcasts B across
            # the leading batch dimension without materializing b copies of B.
            BX = np.matmul(B, Xsafe)
            xb_cross = np.matmul(Xt, BX)

            r2_values = np.empty((safe_local.size, len(combo_columns)), dtype=float)

            try:
                for combo_i, (cols, k) in enumerate(zip(combo_columns, combo_widths)):
                    if abs(total_inertia) < 1e-12:
                        r = np.zeros(safe_local.size, dtype=float)
                    else:
                        Gs = gram[:, cols][:, :, cols]
                        Qs = xb_cross[:, cols][:, :, cols]
                        solved = np.linalg.solve(Gs, Qs)
                        constrained_inertia = np.trace(solved, axis1=1, axis2=2)
                        r = constrained_inertia / total_inertia

                    if type == "adjR2":
                        if n_samples <= k + 1:
                            r = np.zeros_like(r)
                        else:
                            r = 1.0 - (1.0 - r) * (n_samples - 1) / (n_samples - k - 1)

                    r2_values[:, combo_i] = r

                raw_individual = r2_values @ weights.T
                # Preserve historical four-decimal Individual values exactly.
                for pos, local_i in enumerate(safe_local):
                    for j in range(n_items):
                        out[batch_start + local_i, j] = round(
                            float(raw_individual[pos, j]), 4
                        )
            except np.linalg.LinAlgError:
                # Rare numerical failure: retry the whole batch through the
                # Round-1 subset evaluator, which contains projection/pinv fallback.
                batch_fast_failed = True
                out[batch_start:batch_end, :] = np.nan

        fallback_local = (
            np.arange(b, dtype=np.intp)
            if batch_fast_failed
            else np.flatnonzero(~safe_mask)
        )

        for local_i in fallback_local:
            try:
                permuted_groups = [
                    X_batch[local_i, :, starts[g]:starts[g + 1]]
                    for g in range(n_items)
                ]
                r2_values = _dbrda_subset_r2_values_fast(
                    dv_dist,
                    permuted_groups,
                    combo_indices,
                    type=type,
                    add=add,
                    sqrt_dist=sqrt_dist,
                )
                raw_individual = weights @ r2_values
                for j in range(n_items):
                    out[batch_start + local_i, j] = round(
                        float(raw_individual[j]), 4
                    )
            except Exception:
                if not skip_failed:
                    raise
                failed_perms += 1
                out[batch_start + local_i, :] = np.nan

        if verbose:
            while next_progress <= batch_end:
                print(f"  Completed {next_progress}/{n_random} permutations")
                next_progress += 100

    return out, failed_perms


def permu_hp(dv: Union[np.ndarray, pd.DataFrame],
             iv: Union[np.ndarray, pd.DataFrame, List, Dict],
             method: str = "RDA",
             type: str = "adjR2",
             permutations: int = 1000,
             scale: bool = False,
             n_perm: int = 1000,          # for CCA adjR2
             add: bool | str = False,     # False, True/"lingoes", or "cailliez"
             sqrt_dist: bool = False,     # for dbRDA
             n_axes: int = None,          # for dbRDA
             ordered_factors: dict | None = None,
             categorical_factors: list | None = None,
             verbose: bool = True,
             random_state: int | None = None,
             dbrdatype: str = "dbrda",
             distance: str | None = None,
             skip_failed: bool = False,
             **kwargs) -> pd.DataFrame:
    """
    Permutation test for hierarchical partitioning.

    This follows rdacca.hp::permu.hp semantics:
    - ``permutations`` is the total number of values used for the empirical distribution.
    - The observed value is included once, so only ``permutations - 1`` randomized runs
      are performed.
    - For DataFrame input, each original predictor is permuted independently.
    - For dict/list grouped input, all groups are permuted using the same row order.
    - Supplying ``distance`` treats ``dv`` as raw response data and computes the
      db-RDA distance matrix once before the permutation loop.
    - The result matches R ``permu.hp()`` with ``Individual`` and ``Pr(>I)``
      columns. Significance stars are included in the character ``Pr(>I)``
      values using the same spacing rules as R.
    - By default a failed permutation stops the analysis, as in R. Set
      ``skip_failed=True`` to omit failed permutations.
    """

    method = method.upper()
    if method not in {"RDA", "CCA", "DBRDA"}:
        raise ValueError("method must be 'RDA', 'CCA', or 'dbRDA'")

    if type not in {"R2", "adjR2"}:
        raise ValueError("type must be 'R2' or 'adjR2'")

    permutations = int(permutations)
    if permutations < 2:
        raise ValueError("permutations must be at least 2")

    ordered_factors = ordered_factors or {}
    categorical_factors = categorical_factors or []
    rng = np.random.default_rng(random_state)
    cca_rng = rng if method == "CCA" and type == "adjR2" else None

    dv = sanitize_tabular_input(dv, warn=verbose)
    iv = sanitize_tabular_input(iv, warn=verbose)
    iv_is_dataframe_input = isinstance(iv, pd.DataFrame)

    # Prepare distances only once. Recomputing them in every randomized run
    # would be unnecessary because permu.hp permutes iv, not dv.
    dv_for_permutation = (
        prepare_dbrda_response(dv, distance=distance)
        if method == "DBRDA"
        else dv
    )

    n_random = permutations - 1

    if verbose:
        print(f"Please wait: running {n_random} permutations")
        start_time = time.perf_counter()

    # ---- observed result ----
    obs_result = rdacca_hp(
        dv=dv_for_permutation,
        iv=iv,
        method=method,
        type=type,
        scale=scale,
        var_part=False,
        n_perm=n_perm,
        add=add,
        sqrt_dist=sqrt_dist,
        n_axes=n_axes,
        dbrdatype=dbrdatype,
        distance=None,
        ordered_factors=ordered_factors,
        categorical_factors=categorical_factors,
        random_state=cca_rng,
        **kwargs
    )

    obs_individual = obs_result.hier_part["Individual"].to_numpy(dtype=float)
    n_vars = len(obs_individual)

    # ---- build a lightweight internal evaluator for permutations ----
    perm_base_iv, perm_engine = _build_permutation_engine(
        iv=iv,
        method=method,
        type=type,
        scale=scale,
        n_perm=n_perm,
        add=add,
        sqrt_dist=sqrt_dist,
        n_axes=n_axes,
        dbrdatype=dbrdatype,
        ordered_factors=ordered_factors,
        categorical_factors=categorical_factors,
        kwargs=kwargs,
        cca_rng=cca_rng,
    )

    # ---- initialize ----
    perm_individual = np.full((n_random, n_vars), np.nan, dtype=float)
    failed_perms = 0

    # Always infer n from the explanatory variables, not from dv.
    # This is essential for dbRDA when dv is a condensed distance vector.
    n_samples = _infer_n_samples(dv_for_permutation, perm_base_iv)

    # RDA and default dbRDA have dedicated fast permutation paths.  The
    # existing public/statistical semantics are unchanged; only repeated
    # numerical work is reduced.  Prepared logical groups are converted to
    # ndarrays once, then only row indices are shuffled inside the batch loops.
    fast_rda_groups = None
    fast_rda_mode = None
    fast_dbrda_groups = None
    fast_dbrda_mode = None

    def _prepare_fast_groups():
        if isinstance(perm_base_iv, dict):
            groups = [np.asarray(v, dtype=float) for v in perm_base_iv.values()]
            mode = "independent_groups" if iv_is_dataframe_input else "synchronized_groups"
            return groups, mode
        if isinstance(perm_base_iv, list):
            return [np.asarray(v, dtype=float) for v in perm_base_iv], "synchronized_groups"

        base_arr = np.asarray(perm_base_iv, dtype=float)
        if base_arr.ndim == 1:
            base_arr = base_arr.reshape(-1, 1)
        return [base_arr[:, [j]] for j in range(base_arr.shape[1])], "independent_groups"

    if method == "RDA":
        fast_rda_groups, fast_rda_mode = _prepare_fast_groups()
    elif method == "DBRDA" and str(dbrdatype).lower() == "dbrda":
        fast_dbrda_groups, fast_dbrda_mode = _prepare_fast_groups()

    # ---- permutation loop ----
    if fast_rda_groups is not None:
        # Second-round RDA optimization: evaluate the same subset across a batch
        # of permutations with stacked NumPy linear algebra.
        perm_individual, failed_perms = _rda_permutation_individuals_batched(
            dv=dv_for_permutation,
            base_groups=fast_rda_groups,
            n_random=n_random,
            n_samples=n_samples,
            rng=rng,
            mode=fast_rda_mode,
            type=type,
            scale=scale,
            verbose=verbose,
            skip_failed=skip_failed,
        )
    elif fast_dbrda_groups is not None:
        # dbRDA Round-2 optimization: prepare the response-side Gower matrix once
        # for the whole permutation test and batch G=X'X / Q=X'BX calculations.
        perm_individual, failed_perms = _dbrda_permutation_individuals_batched(
            dv_dist=dv_for_permutation,
            base_groups=fast_dbrda_groups,
            n_random=n_random,
            n_samples=n_samples,
            rng=rng,
            mode=fast_dbrda_mode,
            type=type,
            add=add,
            sqrt_dist=sqrt_dist,
            verbose=verbose,
            skip_failed=skip_failed,
        )
    else:
        for i in range(n_random):
            if verbose and (i + 1) % 100 == 0:
                print(f"  Completed {i + 1}/{n_random} permutations")

            if iv_is_dataframe_input and isinstance(perm_base_iv, dict):
                permuted_iv = _permute_grouped_dict_independently(perm_base_iv, n_samples, rng)
            else:
                permuted_iv = _permute_variables(perm_base_iv, n_samples, rng)

            try:
                perm_result = perm_engine(dv_for_permutation, permuted_iv)
                perm_individual[i, :] = perm_result.hier_part["Individual"].to_numpy(dtype=float)

            except Exception as e:
                if not skip_failed:
                    raise
                failed_perms += 1
                if verbose:
                    print(f"Warning: permutation {i + 1} failed: {e}")

    # ---- summarize failures ----
    if verbose:
        print(f"Failed permutations: {failed_perms}/{n_random}")

    valid_mask = ~np.isnan(perm_individual).any(axis=1)
    valid_perm = perm_individual[valid_mask]

    if valid_perm.shape[0] == 0:
        raise RuntimeError(
            "All permutations failed. "
            "Please inspect categorical/ordered factor preprocessing and permutation handling."
        )

    # ---- p-values ----
    p_values = _calculate_p_values(
        obs_values=obs_individual,
        perm_values=valid_perm,
        n_perm=valid_perm.shape[0] + 1,
    )

    result_df = _create_result_dataframe(obs_result, p_values)

    if verbose:
        elapsed_time = time.perf_counter() - start_time
        print(f"Permutation test completed in {elapsed_time:.2f} seconds")

    return result_df


def _infer_n_samples(dv, iv) -> int:
    """
    Infer sample size from iv first, then dv.

    Permutation is applied to explanatory variables, so iv is the reliable source
    of sample size. This also prevents a dbRDA condensed distance vector of length
    n * (n - 1) / 2 from being mistaken for n samples.
    """
    if isinstance(iv, pd.DataFrame):
        return iv.shape[0]

    if isinstance(iv, dict):
        first = next(iter(iv.values()))
        return first.shape[0] if hasattr(first, "shape") else len(first)

    if isinstance(iv, list):
        first = iv[0]
        return first.shape[0] if hasattr(first, "shape") else len(first)

    if iv is not None:
        arr = np.asarray(iv)
        if arr.ndim >= 1:
            return arr.shape[0]

    if isinstance(dv, pd.DataFrame):
        return dv.shape[0]

    if isinstance(dv, np.ndarray):
        arr = np.asarray(dv)
        if arr.ndim == 2:
            return arr.shape[0]

    raise ValueError("Cannot infer sample size from inputs.")


def _permute_dataframe_rows(df: pd.DataFrame, perms: np.ndarray) -> pd.DataFrame:
    return df.iloc[perms].reset_index(drop=True)


def _permute_array_rows(value, perms: np.ndarray):
    arr = np.asarray(value)
    if arr.ndim == 1:
        return arr[perms]
    return arr[perms, :]


def _permute_grouped_dict_independently(iv: Dict, n_samples: int, rng) -> Dict:
    """
    Permute each logical predictor group independently.

    Used for original DataFrame input after one-time factor encoding. A categorical
    variable expanded to multiple dummy columns stays together within its group,
    but different original variables receive different permutations, matching the
    data.frame branch of rdacca.hp::permu.hp.
    """
    out = {}
    for k, v in iv.items():
        perms = rng.permutation(n_samples)
        if isinstance(v, pd.DataFrame):
            out[k] = _permute_dataframe_rows(v, perms)
        else:
            out[k] = _permute_array_rows(v, perms)
    return out


def _permute_dataframe_columns(df: pd.DataFrame, n_samples: int, rng) -> pd.DataFrame:
    """
    Permute each column of a DataFrame independently while preserving
    DataFrame structure, column names, and dtypes as much as possible.
    """
    out = df.copy().reset_index(drop=True)

    for col in out.columns:
        perms = rng.permutation(n_samples)
        out[col] = out[col].iloc[perms].to_numpy()

    return out


def _permute_ndarray_columns(arr: np.ndarray, n_samples: int, rng) -> np.ndarray:
    """
    Permute each column of an ndarray independently.
    """
    arr = np.asarray(arr).copy()

    if arr.ndim == 1:
        perms = rng.permutation(n_samples)
        return arr[perms]

    for j in range(arr.shape[1]):
        perms = rng.permutation(n_samples)
        arr[:, j] = arr[perms, j]

    return arr


def _permute_variables(
    iv: Union[np.ndarray, pd.DataFrame, List, Dict],
    n_samples: int,
    rng=None,
):
    """
    Permute predictor variables while preserving structure.

    Backward-compatible:
    - existing calls like _permute_variables(iv, n_samples) still work
    - optimized internal calls may pass rng explicitly
    """
    if rng is None:
        rng = np.random.default_rng()

    # ---- grouped dict input: synchronized row permutation across groups ----
    if isinstance(iv, dict):
        perms = rng.permutation(n_samples)
        out = {}

        for k, v in iv.items():
            if isinstance(v, pd.DataFrame):
                out[k] = _permute_dataframe_rows(v, perms)
            else:
                out[k] = _permute_array_rows(v, perms)
        return out

    # ---- grouped list input: synchronized row permutation across groups ----
    if isinstance(iv, list):
        perms = rng.permutation(n_samples)
        out = []

        for v in iv:
            if isinstance(v, pd.DataFrame):
                out.append(_permute_dataframe_rows(v, perms))
            else:
                out.append(_permute_array_rows(v, perms))
        return out

    # ---- single DataFrame input ----
    if isinstance(iv, pd.DataFrame):
        return _permute_dataframe_columns(iv, n_samples, rng)

    # ---- ndarray input ----
    return _permute_ndarray_columns(np.asarray(iv), n_samples, rng)


def _calculate_p_values(obs_values: np.ndarray,
                        perm_values: np.ndarray,
                        n_perm: int | None = None) -> np.ndarray:
    """
    Calculate p-values using the rdacca.hp::permu.hp ECDF formula.

    ``n_perm`` is the total permutations argument, including the observed value.
    If omitted, it is inferred as one observed value plus the number of valid
    randomized runs.
    """
    obs_values = np.asarray(obs_values, dtype=float)
    perm_values = np.asarray(perm_values, dtype=float)

    total_permutations = int(n_perm) if n_perm is not None else perm_values.shape[0] + 1
    decimals = len(str(total_permutations))

    p_values = np.zeros(len(obs_values), dtype=float)

    for i in range(len(obs_values)):
        x = np.concatenate(([obs_values[i]], perm_values[:, i]))
        ecdf_at_obs = np.mean(x <= obs_values[i])
        p = 1.0 - ecdf_at_obs + 1.0 / (total_permutations + 1.0)
        # R's round() uses IEC 60559 ties-to-even rounding. NumPy follows
        # that rule, while Python's built-in round can differ for decimal
        # halfway values because of their binary representation.
        p_values[i] = float(np.round(p, decimals))

    return p_values


def _create_result_dataframe(obs_result, p_values: np.ndarray) -> pd.DataFrame:
    """
    Format permutation results like R permu.hp or as the expanded Python table.
    """
    hier_part = obs_result.hier_part
    return pd.DataFrame(
        {
            "Individual": hier_part["Individual"].to_numpy(dtype=float),
            "Pr(>I)": [_format_r_p_value(value) for value in p_values],
        },
        index=hier_part.index,
    )


def _format_r_p_value(p_value: float) -> str:
    """Combine the rounded p-value and stars as R permu.hp prints them."""
    if p_value <= 0.001:
        suffix = " ***"
    elif p_value <= 0.01:
        suffix = "  **"
    elif p_value <= 0.05:
        suffix = "   *"
    else:
        suffix = "    "
    return f"{p_value:g}{suffix}"


def _format_significance(p_value: float) -> str:
    """
    Convert p-value to significance stars, following rdacca.hp::permu.hp.
    """
    if p_value <= 0.001:
        return "***"
    elif p_value <= 0.01:
        return "**"
    elif p_value <= 0.05:
        return "*"
    else:
        return ""
